const {chromium,expect}=require('@playwright/test');const {spawn}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');
(async()=>{
 const server=spawn(path.resolve('.venv/Scripts/python.exe'),['-u','tests/catalog_server.py'],{windowsHide:true,env:{...process.env,PYTHONUTF8:'1',FRIDAY_DESKTOP_PID:String(process.pid)}});
 let browser,logs='';server.stderr.on('data',b=>logs+=b.toString());
 try{
  await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:17839/api/health')).ok}catch{return false}},{timeout:20000}).toBe(true);
  const runtime=JSON.parse(fs.readFileSync('data/catalog-test-runtime.json'));
  browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required',`--use-file-for-fake-audio-capture=${path.resolve('data/wake-ambient.wav')}%noloop`]});
  const context=await browser.newContext({viewport:{width:1440,height:960},permissions:['microphone']});
  const page=await context.newPage();await page.addInitScript(()=>{if(!localStorage.getItem('friday-prefs'))localStorage.setItem('friday-prefs',JSON.stringify({voice:false,wake:false}));});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${runtime.port}/#token=${runtime.token}`);
  await expect(page.getByRole('heading',{name:'Чем могу помочь?'})).toBeVisible();
  await expect(page.locator('.inspector')).toHaveCount(0);
  await page.getByRole('button',{name:'Только чат',exact:true}).click();await expect(page.locator('.interactive-orb')).toHaveCount(0);await page.getByRole('button',{name:'С ядром',exact:true}).click();
  await expect(page.getByRole('switch',{name:'Голосовые ответы'})).toBeVisible();
  const canvas=page.locator('.interactive-orb canvas');
  await page.getByRole('button',{name:'Приостановить анимацию'}).click();
  await expect(page.locator('.interactive-orb')).toHaveClass(/still/);
  await page.waitForTimeout(100);const still=await canvas.evaluate(el=>el.toDataURL());await page.waitForTimeout(180);expect((await canvas.evaluate(el=>el.toDataURL()))===still,'Paused canvas stays still').toBe(true);
  await page.screenshot({path:'data/refined-home.png'});
  await page.getByRole('button',{name:'Включить анимацию'}).click();
  const box=await canvas.boundingBox();await page.mouse.move(box.x+170,box.y+130);await page.mouse.down();await page.mouse.move(box.x+255,box.y+180,{steps:16});await page.mouse.up();
  await expect(page.locator('.orb-tip')).toHaveCSS('opacity','1');await page.screenshot({path:'data/refined-orb.png'});
  await canvas.focus();await page.keyboard.press('Space');await expect(page.locator('.interactive-orb')).toHaveClass(/still/);
  await page.waitForTimeout(100);expect((await canvas.evaluate(el=>el.toDataURL()))!==still,'Dragging changes orientation').toBe(true);
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await expect(page.getByRole('button',{name:'Настройки',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('button',{name:'Помощник',exact:true})).not.toHaveClass(/selected/);
  await expect(page.getByRole('heading',{name:'Голос Пятницы',exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Тембр голоса'}).selectOption('qwen-serena');
  await page.getByRole('button',{name:'Послушать голос',exact:true}).click();
  await expect(page.locator('.voice-progress')).toContainText('Воспроизведение',{timeout:5000});
  await expect(page.locator('.voice-progress')).toHaveCount(0,{timeout:10000});
  await expect(page.getByRole('heading',{name:'Цветовая тема'})).toHaveCount(0);
  await page.screenshot({path:'data/refined-settings.png'});
  await page.getByRole('button',{name:'Проверить микрофон',exact:true}).click();await expect(page.getByRole('meter',{name:'Уровень микрофона'})).toBeVisible();
  await page.getByRole('tab',{name:'Оформление',exact:true}).click();await expect(page.getByRole('meter')).toHaveCount(0);
  await page.getByRole('combobox',{name:'Анимация ядра'}).selectOption('ambient');
  await page.getByRole('button',{name:'Стиль Лаванда'}).click();await page.screenshot({path:'data/refined-appearance.png'});
  await page.getByRole('tab',{name:'Система',exact:true}).click();await expect(page.getByRole('heading',{name:'Локальные модели'})).toBeVisible();
  await page.getByRole('tab',{name:'Система',exact:true}).focus();await page.keyboard.press('ArrowLeft');await expect(page.getByRole('tab',{name:'Оформление',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('button',{name:'Помощник',exact:true}).click();await expect(page.locator('.interactive-orb')).toHaveClass(/ambient/);
  await page.reload();await expect(page.locator('.interactive-orb')).toHaveClass(/ambient/);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('friday-prefs')).theme)).toBe('lavender');
  await page.getByRole('textbox',{name:'Сообщение Пятнице'}).fill('Который час?');await page.getByRole('button',{name:'Отправить',exact:true}).click();await expect(page.locator('.message.assistant .message-text')).toContainText('Сейчас');
  await page.getByRole('button',{name:'Только чат',exact:true}).click();await expect(canvas).toHaveCount(0);
  await page.getByRole('button',{name:'Команды',exact:true}).click();await page.getByRole('textbox',{name:'Поиск команд'}).fill('калькулятора');await expect(page.locator('.catalog-card')).toHaveCount(1);await page.getByRole('button',{name:/Формулировки/}).click();await expect(page.getByRole('button',{name:'Перейди к калькулятору',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Помощник',exact:true}).click();await page.getByRole('button',{name:'С ядром',exact:true}).click();
  await page.setViewportSize({width:1050,height:720});await expect(page.getByRole('textbox',{name:'Сообщение Пятнице'})).toBeInViewport();await expect(page.getByRole('switch',{name:'Голосовые ответы'})).toBeInViewport();await page.screenshot({path:'data/refined-compact.png'});
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(150);const reduced=await canvas.evaluate(el=>el.toDataURL());await page.waitForTimeout(150);expect((await canvas.evaluate(el=>el.toDataURL()))===reduced,'Reduced motion stays still').toBe(true);
  if(errors.length)throw Error(errors.join('\n'));console.log('REFINEMENT PASS: drag/pause/reduced motion, settings groups, microphone cleanup, saved theme and motion, commands, compact layout');
 }catch(e){console.error(logs);throw e;}finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
