const { chromium, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const runtime=JSON.parse(fs.readFileSync('data/runtime.json','utf8'));
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:920},deviceScaleFactor:1});
  await page.addInitScript(()=>{if(!localStorage.getItem('friday-prefs'))localStorage.setItem('friday-prefs',JSON.stringify({wake:false}));});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${runtime.port}/#token=${runtime.token}`);
  await expect(page.getByRole('heading',{name:'Чем могу помочь?'})).toBeVisible();
  await page.screenshot({path:'data/friday-preview.png',fullPage:true});
  await page.getByRole('switch',{name:'Голосовые ответы',exact:true}).click();
  await page.getByRole('textbox',{name:'Сообщение Пятнице'}).fill('Который час?');
  await page.getByRole('button',{name:'Отправить',exact:true}).click();
  await expect(page.locator('.message.assistant .message-text')).toContainText('Сейчас', {timeout:20000});
  await page.getByRole('button',{name:'История',exact:true}).click();
  await expect(page.locator('.history-row').first()).toContainText('Который час');
  await page.getByRole('button',{name:'Команды',exact:true}).click();
  await expect(page.locator('.command-card')).toHaveCount(90);
  await page.getByRole('button',{name:'Мои заметки',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Мои заметки'})).toBeVisible();
  await page.getByRole('button',{name:'Создать',exact:true}).click();
  await page.getByRole('textbox',{name:'Сообщение Пятнице'}).fill('Запиши заметку: Проверка работы Пятницы');
  await page.getByRole('button',{name:'Отправить',exact:true}).click();
  await expect(page.locator('.message.assistant .message-text').last()).toContainText('Заметка сохранена', {timeout:15000});
  await page.getByRole('button',{name:'Мои заметки',exact:true}).click();
  await expect(page.locator('.note-card').first()).toContainText('Проверка работы Пятницы');
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await page.getByRole('combobox',{name:'Тембр голоса'}).selectOption('baya');
  await page.reload();
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Тембр голоса'})).toHaveValue('baya');
  await page.screenshot({path:'data/friday-settings.png',fullPage:true});
  await page.setViewportSize({width:1080,height:760});
  await page.getByRole('button',{name:'Помощник',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Сообщение Пятнице'})).toBeInViewport();
  await page.screenshot({path:'data/friday-compact.png',fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('UI PASS: chat, command, history, note, preferences, responsive layout; no browser errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
