const {chromium,expect}=require('@playwright/test');const fs=require('node:fs');const path=require('node:path');
(async()=>{
  const runtime=JSON.parse(fs.readFileSync('data/runtime.json','utf8'));
  const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream',`--use-file-for-fake-audio-capture=${path.resolve('data/voice-sample.wav')}`]});
  const ctx=await browser.newContext({permissions:['microphone'],viewport:{width:1440,height:960}});const page=await ctx.newPage();
  await page.addInitScript(()=>localStorage.setItem('friday-prefs',JSON.stringify({wake:false})));
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${runtime.port}/#token=${runtime.token}`);
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Микрофон',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Обновить список',exact:true}).click();
  const select=page.getByRole('combobox',{name:'Устройство ввода'});
  await expect(select.locator('option')).not.toHaveCount(1);
  const devices=await select.locator('option').evaluateAll(options=>options.map(o=>({value:o.value,label:o.textContent})));
  const device=devices.find(d=>d.value);
  await select.selectOption(device.value);
  await page.getByRole('button',{name:'Проверить микрофон',exact:true}).click();
  await expect(page.getByRole('button',{name:'Остановить проверку',exact:true})).toBeVisible();
  await expect.poll(()=>page.getByRole('meter',{name:'Уровень микрофона'}).getAttribute('aria-valuenow')).not.toBe('0');
  await page.screenshot({path:'data/microphone-settings.png',fullPage:true});
  await page.getByRole('button',{name:'Остановить проверку',exact:true}).click();
  await page.reload();await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await expect(select).toHaveValue(device.value);
  await expect(page.getByRole('combobox',{name:'Тембр голоса'}).locator('option')).toHaveCount(6);
  await page.getByRole('combobox',{name:'Тембр голоса'}).selectOption('qwen-sohee');
  await page.reload();await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Тембр голоса'})).toHaveValue('qwen-sohee');
  await page.getByRole('button',{name:'Команды',exact:true}).click();
  await expect(page.locator('.command-card')).toHaveCount(90);
  await page.getByRole('textbox',{name:'Поиск команд'}).fill('папки');
  await expect(page.locator('.command-card')).toHaveCount(8);
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('UPGRADE UI PASS: named microphones, selection persistence, live level, six voices, 90 searchable commands');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
